/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev` or `next build`
// and should not be edited by hand. It's stubbed here only because this
// environment can't run those commands to generate it for real. Once you
// run `npm run dev` for the first time, Next.js will overwrite this with
// its actual generated content — that's expected and fine.

// See https://nextjs.org/docs/app/api-reference/config/typescript for more information.
